version: 0.0
os: linux
files:
  - source: /
    destination: /

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      runas: root
  AfterInstall:
    - location: scripts/migrate.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      runas: root
