name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEArw+39r6yT1GvvKqn9y25vtgL8AIUb+sVOHUi0qJA7azYleCv8VZ/
CSBFwHfxCMr2Ba/XqFfHOdP9k+YMwdHloupML63SOX2+i+rpD4d9J0x746A8VC4LP6ggtP
miUiI/laetPK/1CB5zMik3NyzPyE+1bFX8LqtrKHZFg00F7WafOOgQMJ6uHAlyxFZgkC2S
maGRlfHS9LAzN/rT1/5Rww9Mh30glvd5FmD0mI4EMnBGj/xsE52O+mlNPd7GWXN1AoJutk
wWlkgmJl3QP5tSTcxWAvMt/0spmXiWYbn3T7WEwxLTCqunQnb2eZip82YWj3BpMbnBHLMo
EQ7UiX7/5EmKwFfBcYJoum+qIq+REy67DT3H1FpmUOPdohN5wYcsfTB9FP39Jg0BBx9hDa
xNz3XwNaEXwXUs4ibN+8vAtWCrRHhNTRdWyZAujhEOFxCYlM01uCvgDcdQDWgDczb57iTI
oAxMv7Wu6vKFo5LFeSY7ihG+wTnQtKJz0/TVBpmY+Y86foZZKPnGpdBEBd2E2W/8x7yBj0
FCYF794Tl4rJdWgE6a6GdltvsqQio1+x4als6MXW4JjNZfIG71KWGx0nxGCrudnO4lDH38
a1jwUA/I4MKSiURQJ/boz+OZzYrEpFHbfFTzZ+knbh3N0Jx0MOnIA5gMdzMw4P/vHwNiyl
kAAAdIsQArTrEAK04AAAAHc3NoLXJzYQAAAgEArw+39r6yT1GvvKqn9y25vtgL8AIUb+sV
OHUi0qJA7azYleCv8VZ/CSBFwHfxCMr2Ba/XqFfHOdP9k+YMwdHloupML63SOX2+i+rpD4
d9J0x746A8VC4LP6ggtPmiUiI/laetPK/1CB5zMik3NyzPyE+1bFX8LqtrKHZFg00F7Waf
OOgQMJ6uHAlyxFZgkC2SmaGRlfHS9LAzN/rT1/5Rww9Mh30glvd5FmD0mI4EMnBGj/xsE5
2O+mlNPd7GWXN1AoJutkwWlkgmJl3QP5tSTcxWAvMt/0spmXiWYbn3T7WEwxLTCqunQnb2
eZip82YWj3BpMbnBHLMoEQ7UiX7/5EmKwFfBcYJoum+qIq+REy67DT3H1FpmUOPdohN5wY
csfTB9FP39Jg0BBx9hDaxNz3XwNaEXwXUs4ibN+8vAtWCrRHhNTRdWyZAujhEOFxCYlM01
uCvgDcdQDWgDczb57iTIoAxMv7Wu6vKFo5LFeSY7ihG+wTnQtKJz0/TVBpmY+Y86foZZKP
nGpdBEBd2E2W/8x7yBj0FCYF794Tl4rJdWgE6a6GdltvsqQio1+x4als6MXW4JjNZfIG71
KWGx0nxGCrudnO4lDH38a1jwUA/I4MKSiURQJ/boz+OZzYrEpFHbfFTzZ+knbh3N0Jx0MO
nIA5gMdzMw4P/vHwNiylkAAAADAQABAAACAA8NV/EEVoqRaH3dYpHTQaxSITyiwSUaXnm7
QKJBxzloajsA1b/3gvbC6pxw862g3eSBSRa1bXDgdGY6GpCzvn3yjVhwJqpA0JhxO1bVfI
Jbhi99QJKwXtE7YIyPBlDvlu4EO9YC/xuSmq8OcivxU3BSwjOtdQCCRrV07ecrQT43W6tl
8LZtfmT0vwR4tNbQxFEnXkA5Sb02RUEj9QEWYetWrmrb7GhuoN+2uHFBjMTVeIu61YQeQQ
Pw9+5A8GcSkVYE5wYPpsWHMJiN6nD9pub/kcmxJRxVVx9WCgAfIE+fOOoY/UJmnfwOBIVS
BhLijUAKF1FqOluAYAqPbuDfpZrT6yoEyL75Yw9RNoVXtQqa7HdbJvPh/JK3iJMoLqt1Ng
mhwQfOUDm/WE9AkKud6F9krKY/LVN5AnUqk+0cIDqekVFgwdS/408qLbu/t1ZVhM+WF7i1
zZKRGRa4L2hMbk4Gis/lOEtD+ORNDiTlAS2XyPWf2SngTFNKbc6LflcQmfzghj1xlqjksu
UjNAqdy34nNQL93/yh3MyeMbVNCE1PkzX4xjUenaR2G0Z2gxXGHUjZDvKlG297rbd2ueln
l3xaPsPymDZotprzVBJnE/LkS2EnDNCYig+ZoG4ial6YtVu7GFEo0TjMRVn3obUHi/kCqX
hnCj6RXleaVgZmJC8BAAABAGWb4Z0qfFn/fMcZ9SayuPb4wfakkeZOsFL2WSpoVJ4/FQNB
Nc5H8T4m6bhIwYpyLC0S6sH9lmeFz5A8dWq0JnHKhsreoDPRZsFctwDuwxZVt0I9lYeTnw
6nOCWpYi5FkVCMjRB7S3tPwdSu0U3tY4HsyA/I0RM9mNHSJAqkGlDTwR5vl/9oK02b4xwP
RY0S1JVokzlg/GrtBdcZ6KwIadBPv/ixlCPXwY6pdNk9d3WRx8YGrFfFERUyzbf5bcB2C8
L+2v2ehcFAS7l3FgJW4/Sdf+Q99WhIwQpRDL+hKh1vWCRsYuRwwReqkH8rWP6CH1y3DfJb
tScbDVZDte3KGK4AAAEBAODv6KTICyjUrumvJQ+147TZB+63rcRBoJB74DZOnM/kUgJwMJ
simiYwadFqowYo3SQs39GSTutSe9BVNP/la09ImYlLICEETDImPmVfgakxOcyHKFI6RN0+
OnBa3FWBlfrch2vAYkJ43w282MlPJivQXIeGh/RsAA6bdX6rq16iaWHu51ke+tLc5G3w24
+9tjYnB6tyYLbAW3EuNZSdFkOmwj/6ZE8E6uqmQlShPbG4dw+MFOzpg4Y7QvrJ+lZGiejq
cKbcq1JPy6Mj/EhnQkBVOCTgwcZNbuE3NJ7NjDdpJudagvn3heBO44IAKA00YfsUxtDNqQ
LEMiNJ9olwOfkAAAEBAMc8k9Qah42vc/SQtDLZ8dQmVdQo9ECfaNvjBUspy/7yz+t2/fKj
qfNZ4LqXDM8fezLp9F7T94sVOVwxGgW4Lujo6rbkfJGlWi6bmYUbkZgk1zavQJiIdyeZFB
oiaV3r/UO7648MjCPtkpjZmoh+VpGhlbhukihDbHH+wkImJp/oL3pW/rhgLv+3YW5D0Wdw
6cUpj2p3mmZHwXcWPysIF+ZbfV1wxgXO02+FvsmnQzTpAifF0+15DZQMpMgyoN7EGjQVxE
T+UeynKCTOFoOYLwJGqYzuoGfyc9zzLGFZxSkzN/pVh/SFawe0DNAQI2/m93kPI9v6RNNL
4jZ6VE8gK2EAAAAQZ2VvYXVndXN0aW9uLmNvbQECAw==" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 54.242.37.235 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@54.242.37.235 'cd /auditions && ./deploy.sh'

      - name: Clean up
        run: |
          rm -f ~/.ssh/id_rsa
