version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auditions_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    command: gunicorn auditions.wsgi:application --bind 0.0.0.0:8000

  db:
    image: postgres:14
    container_name: auditions_db
    environment:
      POSTGRES_DB: movieaudition
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 65376537
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
