# Generated by Django 5.0.7 on 2024-08-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
