# Generated by Django 5.0.3 on 2024-09-27 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditions', '0002_remove_movie_age_application_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='last_registration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 18, 22, 3, 722297, tzinfo=datetime.timezone.utc)),
        ),
    ]
