# Generated by Django 5.0.3 on 2024-09-29 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditions', '0005_alter_application_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='last_registration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 3, 57, 19, 592826, tzinfo=datetime.timezone.utc)),
        ),
    ]
