# Generated by Django 5.0.3 on 2024-08-31 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditions', '0007_application_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='age',
        ),
        migrations.AddField(
            model_name='movie',
            name='age_end',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='age_start',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
