# Generated by Django 5.0.3 on 2024-09-29 12:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditions', '0010_customuser_gender_alter_movie_last_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='last_registration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 12, 45, 38, 377337, tzinfo=datetime.timezone.utc)),
        ),
    ]
