# Generated by Django 5.0.3 on 2024-09-21 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditions', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='last_registration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 21, 4, 8, 42, 530121, tzinfo=datetime.timezone.utc)),
        ),
    ]
