# Generated by Django 5.0.3 on 2024-09-22 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditions', '0011_movie_last_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='last_registration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 22, 6, 45, 3, 124208, tzinfo=datetime.timezone.utc)),
        ),
    ]
