# Generated by Django 5.0.3 on 2024-09-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditions', '0011_application_cv_alter_application_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='location',
            new_name='location_name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='last_registration_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
