# Generated by Django 5.0.3 on 2024-09-30 03:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditions', '0012_rename_location_movie_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='last_registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
