# Generated by Django 5.0.3 on 2024-10-04 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditions', '0013_movie_last_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='last_registration_date',
        ),
    ]
