name: Deploy Django to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up SSH for EC2 access
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Add EC2 Host to Known Hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

    - name: Build Docker Image
      run: |
        docker build -t geoaugustine/audition .

    - name: Push Docker Image to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        docker push geoaugustine/audition

    - name: Deploy to EC2
      run: |
        # Save the EC2 private key to a file
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ec2_key.pem
        chmod 400 ec2_key.pem
        
        # SSH into EC2 and deploy
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Update package index and install Docker if needed
          sudo apt-get update
          if ! command -v docker &> /dev/null; then
            sudo apt-get install -y docker.io docker-compose
            sudo systemctl start docker
            sudo systemctl enable docker
          fi
          
          # Navigate to the project directory
          cd /home/ubuntu/movieaudition || exit
          git stash

          # Clean up untracked files and pull the latest changes
          git clean -f
          git pull origin main || exit
          
          # Stop current Docker containers and remove them
          sudo docker-compose down

          # Pull the latest Docker image and restart containers
          sudo docker-compose pull
          sudo docker-compose up -d
        EOF

    - name: Clean up SSH key
      run: rm ec2_key.pem