name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python manage.py test

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to AWS EC2
        env:
          EC2_PUBLIC_IP: ${{ secrets.34.232.69.43 }}
        run: |
          ssh -o "StrictHostKeyChecking=no" -i ~/.ssh/id_rsa ubuntu@${{ env.34.232.69.43 }} << 'EOF'
            # Navigate to the project directory
            cd audition

            # Remove the old virtual environment (optional)
            rm -rf venv

            # Create a new virtual environment
            python3 -m venv venv

            # Activate the virtual environment
            source venv/bin/activate

            # Install the dependencies in the new virtual environment
            pip install -r requirements.txt

            # Pull the latest code from the repository
            git pull origin master

            # Restart the application using supervisor
            sudo supervisorctl restart all
          EOF
